### ISSUE TITLE
Расширить категории точек (каждая группа - аккордеон).

### ISSUE THREAD

**Issue by AkpoFlash** [corgilab/mynorthwest#46]
Подкатегории ниже.

1) Дети: качели, горки, песочницы, батуты, скалодром, лабиринт
2) Спорт:  велопрокат, тренажеры, настольный теннис, волейбол, баскетбол,  скейтпарк, поле для мини-футбола
3) Культура: соседский центр, сцена, буккроссинг, миниферма, беседка, кафе
4) События: ярмарки, кино на открытом воздухе, дискотека, мастер-классы, лекции, гастрономический фестиваль

**Comment by repushko** [comment]
done
